version: '3.3'

networks:
  backend:

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: django-api
    env_file: 
      - ./.env
    command: ./src/manage.py runserver 0:8000
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    env_file: 
      - ./.env
    networks:
      - backend
    volumes:
      - /dbdata:/dbdata